# Generated by Django 5.1.10 on 2025-09-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongmsp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessments',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='questions',
            name='scale_choice_labels',
            field=models.JSONField(blank=True, null=True, verbose_name='Scale Choice Labels'),
        ),
    ]
