# Generated by Django 5.1.10 on 2025-10-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongmsp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorganizations',
            name='is_coach',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Coach'),
        ),
    ]
