# Generated by Django 5.1.10 on 2025-09-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongmsp_app', '0002_assessments_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachcontent',
            name='purpose',
            field=models.CharField(blank=True, choices=[('lessonpackage', 'Lesson-package'), ('12sessions', ' 12-sessions'), ('talkingpoints', ' talking-points'), ('feedbackreport', ' feedback-report'), ('parentemail', ' parent-email')], max_length=14, null=True, verbose_name='Purpose'),
        ),
    ]
