# Generated by Django 5.1.10 on 2025-10-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongmsp_app', '0002_userorganizations_is_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='waiver_signed',
            field=models.BooleanField(default=False, verbose_name='Waiver Signed'),
        ),
    ]
