# Generated by Django 5.1.10 on 2025-10-16 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongmsp_app', '0003_coachcontent_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponses',
            name='assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='strongmsp_app.assessments', verbose_name='Assessment'),
        ),
    ]
