# Generated by Django 5.1.10 on 2025-10-30 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strongmsp_app', '0003_users_waiver_signed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='real_name',
        ),
    ]
