# Generated by Django 5.1.10 on 2025-10-16 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongmsp_app', '0004_add_assessment_to_question_responses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(verbose_name='Message')),
                ('seen', models.BooleanField(default=False, verbose_name='Seen')),
                ('remind_time', models.DateTimeField(blank=True, null=True, verbose_name='Remind Time')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link')),
                ('expires', models.DateTimeField(blank=True, null=True, verbose_name='Expires')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-seen', '-remind_time'],
                'abstract': False,
            },
        ),
    ]
