# Generated by Django 5.1.10 on 2025-10-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongmsp_app', '0005_notifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AddField(
            model_name='notifications',
            name='auto_send',
            field=models.BooleanField(default=False, help_text='Automatically send via this channel', verbose_name='Auto Send'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='channel',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('email', 'Email'), ('sms', 'SMS')], default='dashboard', max_length=20, verbose_name='Channel'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='delivery_error',
            field=models.TextField(blank=True, null=True, verbose_name='Delivery Error'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=20, verbose_name='Delivery Status'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='message_html',
            field=models.TextField(blank=True, help_text='HTML version for email', null=True, verbose_name='HTML Message'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='message_text',
            field=models.TextField(blank=True, help_text='Plain text version for SMS and plain email', null=True, verbose_name='Text Message'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='notification_group',
            field=models.UUIDField(blank=True, help_text='Groups related notifications across channels', null=True, verbose_name='Notification Group'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('agent-response', 'Agent Response'), ('coach-content', 'Coach Content'), ('payment', 'Payment'), ('invoice', 'Invoice'), ('assessment-submitted', 'Assessment Submitted')], max_length=30, null=True, verbose_name='Notification Type'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sent At'),
        ),
        migrations.AddIndex(
            model_name='notifications',
            index=models.Index(fields=['channel', 'delivery_status'], name='strongmsp_a_channel_18902b_idx'),
        ),
        migrations.AddIndex(
            model_name='notifications',
            index=models.Index(fields=['notification_group'], name='strongmsp_a_notific_2397ab_idx'),
        ),
        migrations.AddIndex(
            model_name='notifications',
            index=models.Index(fields=['recipient', 'seen'], name='strongmsp_a_recipie_73fa97_idx'),
        ),
    ]
