# Generated by Django 5.1.10 on 2025-10-16 08:47

import django.db.models.deletion
import strongmsp_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongmsp_app', '0007_add_assessment_to_agent_responses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='athlete',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='course',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='preferred_coach',
        ),
        migrations.AddField(
            model_name='payments',
            name='features_snapshot',
            field=models.JSONField(blank=True, help_text='Copy of product features at purchase time', null=True, verbose_name='Features Snapshot'),
        ),
        migrations.AddField(
            model_name='payments',
            name='post_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='strongmsp_app.assessments', verbose_name='Post-Assessment'),
        ),
        migrations.AddField(
            model_name='payments',
            name='pre_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='strongmsp_app.assessments', verbose_name='Pre-Assessment'),
        ),
        migrations.AddField(
            model_name='payments',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Customer ID'),
        ),
        migrations.AddField(
            model_name='payments',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Payment Intent ID'),
        ),
        migrations.AddField(
            model_name='payments',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Subscription ID'),
        ),
        migrations.AlterField(
            model_name='agentresponses',
            name='assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='strongmsp_app.assessments', verbose_name='Assessment'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], max_length=10, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='PaymentAssignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Athlete')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('coaches', models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Coaches')),
                ('parents', models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Parents')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='strongmsp_app.payments', verbose_name='Payment')),
            ],
            options={
                'verbose_name': 'Payment Assignment',
                'verbose_name_plural': 'Payment Assignments',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('stripe_product_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Product ID')),
                ('stripe_price_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Price ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('features', models.JSONField(blank=True, help_text='JSON containing agents, content_variations, and assessment counts', null=True, verbose_name='Features')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=strongmsp_app.models.upload_file_path, verbose_name='Icon')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to=strongmsp_app.models.upload_file_path, verbose_name='Cover Photo')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='payments',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='strongmsp_app.products', verbose_name='Product'),
        ),
    ]
