# Generated by Django 5.1.10 on 2025-10-16 09:48

import strongmsp_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongmsp_app', '0008_remove_payments_athlete_remove_payments_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=strongmsp_app.models.upload_file_path, verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='users',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=strongmsp_app.models.upload_file_path, verbose_name='Photo'),
        ),
    ]
