# Generated by Django 5.1.10 on 2025-10-16 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('strongmsp_app', '0009_add_avatar_photo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='discount_applied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount Applied'),
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Organization Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Subdomain Slug')),
                ('custom_logo_base64', models.TextField(blank=True, null=True, verbose_name='Custom Logo (Base64)')),
                ('branding_palette', models.JSONField(blank=True, help_text='{"light": {"primary": {"main": "#877010"}, "secondary": {"main": "#2a74b7"}}, "dark": {...}}', null=True, verbose_name='Color Palette')),
                ('branding_typography', models.JSONField(blank=True, help_text='{"fontFamily": "Montserrat"}', null=True, verbose_name='Typography Settings')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contact Phone')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Featured')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_organizations', to='strongmsp_app.products')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_products', to='strongmsp_app.organizations')),
            ],
            options={
                'verbose_name': 'Organization Product',
                'verbose_name_plural': 'Organization Products',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='payments',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='strongmsp_app.organizations', verbose_name='Organization'),
        ),
        migrations.CreateModel(
            name='SignUpCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Sign-up Code')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('free', 'Free Access')], default='percentage', max_length=10, verbose_name='Discount Type')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount Value')),
                ('max_uses', models.IntegerField(blank=True, help_text='Leave blank for unlimited', null=True, verbose_name='Max Uses')),
                ('current_uses', models.IntegerField(default=0, verbose_name='Current Uses')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Valid From')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Valid Until')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('applicable_products', models.ManyToManyField(blank=True, related_name='signup_codes', to='strongmsp_app.products')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signup_codes', to='strongmsp_app.organizations')),
            ],
            options={
                'verbose_name': 'Sign-up Code',
                'verbose_name_plural': 'Sign-up Codes',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='payments',
            name='signup_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='strongmsp_app.signupcodes', verbose_name='Sign-up Code Used'),
        ),
        migrations.CreateModel(
            name='UserOrganizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Joined At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='Django Groups defining roles/permissions within this organization', related_name='user_org_memberships', to='auth.group', verbose_name='Groups')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_users', to='strongmsp_app.organizations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Organization',
                'verbose_name_plural': 'User Organizations',
                'abstract': False,
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
