# Generated by Django 5.1.10 on 2025-10-17 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongmsp_app', '0011_move_assessments_to_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponses',
            name='assessment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='strongmsp_app.assessments', verbose_name='Assessment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionresponses',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Athlete'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionresponses',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='strongmsp_app.questions', verbose_name='Question'),
            preserve_default=False,
        ),
    ]
