# Generated by Django 5.1.10 on 2025-10-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongmsp_app', '0012_alter_questionresponses_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentassignments',
            name='post_assessment_submitted',
            field=models.BooleanField(default=False, verbose_name='Post-Assessment Submitted'),
        ),
        migrations.AddField(
            model_name='paymentassignments',
            name='post_assessment_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Post-Assessment Submitted At'),
        ),
        migrations.AddField(
            model_name='paymentassignments',
            name='pre_assessment_submitted',
            field=models.BooleanField(default=False, verbose_name='Pre-Assessment Submitted'),
        ),
        migrations.AddField(
            model_name='paymentassignments',
            name='pre_assessment_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pre-Assessment Submitted At'),
        ),
    ]
