# Generated by Django 5.1.10 on 2025-10-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongmsp_app', '0013_add_assessment_submission_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentassignments',
            name='post_assessment_submitted',
        ),
        migrations.RemoveField(
            model_name='paymentassignments',
            name='pre_assessment_submitted',
        ),
        migrations.AddField(
            model_name='users',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Birthdate'),
        ),
        migrations.AddField(
            model_name='users',
            name='ethnicity',
            field=models.JSONField(blank=True, help_text='Array of ethnicity choices - allows multiple selection', null=True, verbose_name='Ethnicity'),
        ),
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('rather_not_say', 'Rather Not Say')], max_length=15, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='users',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Zip Code'),
        ),
    ]
