# Generated by Django 5.1.10 on 2025-01-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strongmsp_app', '0014_remove_assessment_submission_booleans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_types',
        ),
    ]
