# Generated by Django 5.1.10 on 2025-10-18 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strongmsp_app', '0015_remove_user_types_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='confidence_score',
        ),
    ]
