# Generated by Django 5.1.10 on 2025-10-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongmsp_app', '0016_remove_users_confidence_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='prompt_templates',
            field=models.ManyToManyField(blank=True, related_name='payments', to='strongmsp_app.prompttemplates', verbose_name='Prompt Templates'),
        ),
    ]
