# Generated by Django 5.1.10 on 2025-10-20 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongmsp_app', '0017_payments_prompt_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentresponses',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='strongmsp_app.paymentassignments', verbose_name='Payment Assignment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coachcontent',
            name='assignments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='strongmsp_app.paymentassignments', verbose_name='Payment Assignment'),
        ),
        migrations.AddField(
            model_name='coachcontent',
            name='athlete_received',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Athlete Received At'),
        ),
        migrations.AddField(
            model_name='coachcontent',
            name='coach_delivered',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Coach Delivered At'),
        ),
        migrations.AddField(
            model_name='coachcontent',
            name='parent_received',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Parent Received At'),
        ),
        migrations.AlterField(
            model_name='agentresponses',
            name='athlete',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Athlete'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agentresponses',
            name='purpose',
            field=models.CharField(choices=[('lesson_plan', 'Lesson Plan'), ('curriculum', 'Curriculum'), ('talking_points', 'Talking Points'), ('feedback_report', 'Feedback Report'), ('scheduling_email', 'Scheduling Email')], max_length=50, verbose_name='Purpose'),
        ),
        migrations.AlterField(
            model_name='coachcontent',
            name='purpose',
            field=models.CharField(blank=True, choices=[('lesson_plan', 'Lesson Plan'), ('curriculum', 'Curriculum'), ('talking_points', 'Talking Points'), ('feedback_report', 'Feedback Report'), ('scheduling_email', 'Scheduling Email')], max_length=50, null=True, verbose_name='Purpose'),
        ),
        migrations.AlterField(
            model_name='prompttemplates',
            name='purpose',
            field=models.CharField(choices=[('lesson_plan', 'Lesson Plan'), ('curriculum', 'Curriculum'), ('talking_points', 'Talking Points'), ('feedback_report', 'Feedback Report'), ('scheduling_email', 'Scheduling Email')], max_length=50, verbose_name='Purpose'),
        ),
    ]
