# Generated by Django 5.1.10 on 2025-10-21 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strongmsp_app', '0018_agentresponses_assignment_coachcontent_assignments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coachcontent',
            old_name='assignments',
            new_name='assignment',
        ),
    ]
