# Generated by Django 5.1.10 on 2025-10-24 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongmsp_app', '0019_rename_assignments_coachcontent_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachcontent',
            name='athlete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Athlete'),
        ),
        migrations.AddField(
            model_name='coachcontent',
            name='source_draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_content', to='strongmsp_app.agentresponses', verbose_name='Source Draft'),
        ),
    ]
