# Generated by Django 5.1.10 on 2025-10-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongmsp_app', '0020_coachcontent_athlete_coachcontent_source_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization_logos/', verbose_name='Organization Logo'),
        ),
        migrations.AddField(
            model_name='organizations',
            name='short_name',
            field=models.CharField(blank=True, help_text='Short name displayed in header (e.g., "SMSP")', max_length=100, null=True, verbose_name='Short Name'),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='custom_logo_base64',
            field=models.TextField(blank=True, help_text='Legacy field - use logo field instead', null=True, verbose_name='Custom Logo (Base64)'),
        ),
    ]
