# Generated by Django 5.1.10 on 2025-10-25 06:15

import strongmsp_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongmsp_app', '0021_add_short_name_and_logo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachcontent',
            name='screenshot_dark',
            field=models.ImageField(blank=True, null=True, upload_to=strongmsp_app.models.screenshot_upload_path, verbose_name='Screenshot Dark'),
        ),
        migrations.AddField(
            model_name='coachcontent',
            name='screenshot_light',
            field=models.ImageField(blank=True, null=True, upload_to=strongmsp_app.models.screenshot_upload_path, verbose_name='Screenshot Light'),
        ),
    ]
