# Generated by Django 5.1.10 on 2025-10-25 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strongmsp_app', '0022_coachcontent_screenshot_dark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachcontent',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='coachcontent',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='products',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='products',
            name='icon',
        ),
    ]
