# Generated by Django 5.1.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongmsp_app', '0023_remove_obsolete_image_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='category_performance_mindset',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Performance Mindset Score'),
        ),
        migrations.AddField(
            model_name='users',
            name='category_emotional_regulation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Emotional Regulation Score'),
        ),
        migrations.AddField(
            model_name='users',
            name='category_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Confidence Score'),
        ),
        migrations.AddField(
            model_name='users',
            name='category_resilience_motivation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Resilience & Motivation Score'),
        ),
        migrations.AddField(
            model_name='users',
            name='category_concentration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Concentration Score'),
        ),
        migrations.AddField(
            model_name='users',
            name='category_leadership',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Leadership Score'),
        ),
        migrations.AddField(
            model_name='users',
            name='category_mental_wellbeing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Mental Well-being Score'),
        ),
    ]

