# Generated by Django 5.1.10 on 2025-10-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongmsp_app', '0024_users_category_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='category_total_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Sum of Category Averages for sorting only'),
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
