# Generated by Django 5.1.10 on 2025-10-27 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongmsp_app', '0025_users_category_total_score_delete_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pre_assessment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='strongmsp_app.assessments', verbose_name='Pre-Assessment'),
            preserve_default=False,
        ),
    ]
