# Generated by Django 5.1.10 on 2025-10-27 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strongmsp_app', '0026_alter_products_pre_assessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorganizations',
            name='groups',
        ),
    ]

