# Generated by Django 5.1.10 on 2025-10-29 00:07

from django.db import migrations, models
import django.db.models.deletion


def backfill_denormalized_fields(apps, schema_editor):
    """Backfill organization and pre_assessment fields from payment relationships"""
    PaymentAssignments = apps.get_model('strongmsp_app', 'PaymentAssignments')
    
    # Update all existing PaymentAssignments
    for assignment in PaymentAssignments.objects.all():
        if assignment.payment and assignment.payment.organization:
            assignment.organization = assignment.payment.organization
        if assignment.payment and assignment.payment.product and assignment.payment.product.pre_assessment:
            assignment.pre_assessment = assignment.payment.product.pre_assessment
        assignment.save()


def reverse_backfill_denormalized_fields(apps, schema_editor):
    """Reverse operation - no need to do anything as fields will be dropped"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('strongmsp_app', '0027_remove_userorganizations_groups'),
    ]

    operations = [
        # Skip adding fields since they already exist in the database
        # Just backfill the data to ensure consistency
        migrations.RunPython(
            backfill_denormalized_fields,
            reverse_backfill_denormalized_fields,
        ),
    ]
