# Generated by Django 5.1.10 on 2025-10-29 02:55

from django.db import migrations, models
import django.db.models.deletion


def check_and_add_constraint(apps, schema_editor):
    """Add the unique constraint if it doesn't already exist"""
    with schema_editor.connection.cursor() as cursor:
        # Check if constraint already exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.table_constraints 
            WHERE constraint_name = 'unique_athlete_assessment_org' 
            AND table_name = 'strongmsp_app_paymentassignments'
        """)
        constraint_exists = cursor.fetchone()[0] > 0
        
        if not constraint_exists:
            # Add the unique constraint
            cursor.execute("""
                ALTER TABLE strongmsp_app_paymentassignments 
                ADD CONSTRAINT unique_athlete_assessment_org 
                UNIQUE (athlete_id, organization_id, pre_assessment_id)
            """)


def reverse_constraint(apps, schema_editor):
    """Remove the unique constraint"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE strongmsp_app_paymentassignments 
            DROP CONSTRAINT IF EXISTS unique_athlete_assessment_org
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('strongmsp_app', '0028_add_paymentassignments_denormalized_fields'),
    ]

    operations = [
        # Add the unique constraint using raw SQL
        migrations.RunPython(
            check_and_add_constraint,
            reverse_constraint,
        ),
    ]
