# Generated by Django 5.1.10 on 2025-08-25 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborators', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchemaVersions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.TextField(max_length=4000)),
                ('privacy', models.CharField(blank=True, choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('inviteonly', 'Invite Only'), ('authusers', 'Authenticated Users'), ('onlyme', 'Only Me'), ('archived', 'archived')], default='onlyme', max_length=10, null=True, verbose_name='Privacy')),
                ('assistant_id', models.CharField(max_length=100)),
                ('thread_id', models.CharField(blank=True, max_length=100, null=True)),
                ('message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('run_id', models.CharField(blank=True, max_length=100, null=True)),
                ('openai_model', models.CharField(blank=True, max_length=100, null=True)),
                ('reasoning', models.TextField(blank=True, null=True)),
                ('schema', models.JSONField(blank=True, null=True)),
                ('versions_count', models.PositiveIntegerField(default=0, editable=False)),
                ('version_tree', models.JSONField(blank=True, default=dict, editable=False, null=True)),
                ('version_notes', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='oasheets_app.schemaversions')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project', to='oasheets_app.projectschema')),
            ],
            options={
                'verbose_name': 'Schema Version',
                'verbose_name_plural': 'Schema Versions',
                'ordering': ['-created_at'],
            },
        ),
    ]
